# FOS user config
fos_user:
  db_driver: orm
  firewall_name: main
  user_class: App\Entity\User
  from_email:
    address: "no-reply@autoreview.lt"
    sender_name: "Auto review"
  registration:
    confirmation:
      enabled: false
    #        form:
    #            type: AppBundle\Form\UserRegisterType
#    confirmation:
#      enabled: true
#      template: FOSUserBundle:Registration:email.txt.twig
#      from_email:
#        address:        "no-reply@joeymasip.com"
#        sender_name:    "No Reply Registration"
#  service:
#    mailer: fos_user.mailer.twig_swift
#  resetting:
#    email:
#      template: FOSUserBundle:Resetting:email.txt.twig
  service:
    mailer: fos_user.mailer.twig_swift

